name: Go CI

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4' # Specify the Go version you use

      # Prepare system for GStreamer installation
      - name: Update system and install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libunwind-dev \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev \
            libgstreamer-plugins-bad1.0-dev \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-ugly \
            gstreamer1.0-libav \
            gstreamer1.0-tools \
            gstreamer1.0-x \
            gstreamer1.0-alsa \
            gstreamer1.0-gl \
            gstreamer1.0-gtk3 \
            gstreamer1.0-qt5 \
            gstreamer1.0-pulseaudio

      # Verify GStreamer version
      - name: Verify GStreamer version
        run: gst-launch-1.0 --version

      # Install specific version of Go GStreamer bindings to ensure compatibility
      - name: Install Go GStreamer bindings
        run: |
          go get github.com/go-gst/go-gst@v1.3.0
          go get github.com/go-gst/go-glib@v1.3.0

      # Install Go dependencies
      - name: Install Go dependencies
        run: go mod tidy

      # Run tests
      - name: Run tests
        run: go test ./...
